dist: xenial
os: linux
language: python
python:
- '3.5.2'

before_install:
- pip install -r requirements.txt
- export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
- export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
- export AWS_REGION=$AWS_REGION

install:
- tar -cvf app.tar ./deploy

script:
- aws s3 cp ./app.tar s3://nasirbucket4342/lendit-cicd-test
- aws deploy create-deployment --application-name cicd-test --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name cicd-test --description "221018-v2" --s3-location bucket=nasirbucket4342,bundleType=tar,key=lendit-cicd-test/app.tar