dist: xenial
os: linux

script:
- tar -cvf app.tar ./deploy
- mkdir deploy_tmp
- mv app.tar deploy_tmp/

deploy:
  - provider: s3
    bucket: nasirbucket4342
    region: ap-northeast-2
    on: 
      all_branches: true
    local_dir: deploy_tmp
    upload_dir: cicd-test
    skip_cleanup: true
  - provider: codedeploy
    bucket: nasirbucket4342
    region: ap-northeast-2
    key: cicd-test/app.tar
    bundle_type: tar
    application: test
    deployment_group: test
    on: 
      all_branches: true