dist: xenial
os: linux
language: python
python:
- '3.8'

before_install:
- |
  if ! [ -x "$(command -v aws)" ]; then 
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip 
    sudo ./aws/install 
  fi
- pip3 install flake8
- mkdir upload

install:
- flake8 ./source/ --select=E9,F63,F7,F82 --show-source --statistics
- cp -r source deploy/* upload/
- tar -cvf app.tar ./upload

script:
- aws s3 cp ./app.tar s3://nasirbucket4342/lendit-cicd-test/
- |
  aws deploy create-deployment --application-name test \
  --deployment-config-name CodeDeployDefault.AllAtOnce \
  --deployment-group-name test \
  --s3-location bucket=nasirbucket4342,bundleType=tar,key=lendit-cicd-test/app.tar