dist: xenial
os: linux
language: python
python:
- '3.5.2'

before_install:
- if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi

install:
- tar -cvf app.tar ./deploy

script:
- aws s3 cp ./app.tar s3://nasirbucket4342/lendit-cicd-test
- aws deploy create-deployment --application-name cicd-test --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name cicd-test --description "221018-v2" --s3-location bucket=nasirbucket4342,bundleType=tar,key=lendit-cicd-test/app.tar