version: 0.0
os: linux
files:
  - source: app.py
    destination: /home/ec2-user/
  - source : cicd.conf
    destination: /etc/nginx/conf.d/
permissions:
  - object: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: /restart.sh
      runas: ec2-user