name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello $!"
        echo "- in $!"

# https://github.com/nasir17git/simpletravis
# curl \
#   -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: 토큰" \
#   https://api.github.com/repos/LenditKr/cicd-test/actions/workflows/action.yml/dispatches \
#   -d '{"ref":"master"}'


# > 되는거
# curl \
#   -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: Bearer 토큰" \
#   https://api.github.com/repos/nasir17git/simpletravis/actions/workflows/test.yml/dispatches \
#   -d '{"ref":"main"}'

# > 안되는거
#   curl \
#   -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: Bearer 토큰" \
#   https://api.github.com/repos/nasir17git/simpletravis/actions/workflows/test.yml/dispatches  \
#   -d '{"ref":"main"}'